databases:
  - name: carsdb
    databaseName: carsdb
    user: mysite

services:
  - type: web
    name: air
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: air
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false